# Using Pandas

In [331]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 200)
## to make it possible to display multiple output inside one cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<b>load the data from the vehicles.csv file into pandas data frame

In [332]:
vehicles_df= pd.read_csv("data/vehicles.csv") ## Your Code here
vehicles_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

First exploration of the dataset:

- How many observations does it have?
- Look at all the columns: do you understand what they mean?
- Look at the raw data: do you see anything weird?
- Look at the data types: are they the expected ones for the information the column contains?

CÃ¢te observaÈ›ii are?
UitÄƒ-te la toate coloanele: Ã®nÈ›elegi ce Ã®nseamnÄƒ?
UitÄƒ-te la datele brute: vezi ceva ciudat?
PriviÈ›i tipurile de date: sunt cele aÈ™teptate pentru informaÈ›iile pe care le conÈ›ine coloana?

In [333]:
print("Count before Removing Duplicates: ") # finding duplicate data
vehicles_df.count()

Count before Removing Duplicates:

Make                       35952
Model                      35952
Year                       35952
Engine Displacement        35952
Cylinders                  35952
Transmission               35952
Drivetrain                 35952
Vehicle Class              35952
Fuel Type                  35952
Fuel Barrels/Year          35952
City MPG                   35952
Highway MPG                35952
Combined MPG               35952
CO2 Emission Grams/Mile    35952
Fuel Cost/Year             35952
dtype: int64

In [334]:
print(vehicles_df.isnull().sum()) # Finding the missing or null values

Make                       0
Model                      0
Year                       0
Engine Displacement        0
Cylinders                  0
Transmission               0
Drivetrain                 0
Vehicle Class              0
Fuel Type                  0
Fuel Barrels/Year          0
City MPG                   0
Highway MPG                0
Combined MPG               0
CO2 Emission Grams/Mile    0
Fuel Cost/Year             0
dtype: int64

In [335]:
vehicles_df.cnt = vehicles_df.count
print(vehicles_df.cnt)
## Your Code here

<bound method DataFrame.count of                    Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5
1            AM General     FJ8c Post Office  1984                  4.2
2            AM General  Post Office DJ5 2WD  1985                  2.5
3            AM General  Post Office DJ8 2WD  1985                  4.2
4      ASC Incorporated                  GNX  1987                  3.8
...                 ...                  ...   ...                  ...
35947             smart         fortwo coupe  2013                  1.0
35948             smart         fortwo coupe  2014                  1.0
35949             smart         fortwo coupe  2015                  1.0
35950             smart         fortwo coupe  2016                  0.9
35951             smart         fortwo coupe  2016                  0.9

       Cylinders     Transmission        Drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive
1            6.0  Automatic 3-spd     2-Wheel Drive
2            4.0  Automatic 3-spd  Rear-Wheel Drive
3            6.0  Automatic 3-spd  Rear-Wheel Drive
4            6.0  Automatic 4-spd  Rear-Wheel Drive
...          ...              ...               ...
35947        3.0        Auto(AM5)  Rear-Wheel Drive
35948        3.0        Auto(AM5)  Rear-Wheel Drive
35949        3.0        Auto(AM5)  Rear-Wheel Drive
35950        3.0        Auto(AM6)  Rear-Wheel Drive
35951        3.0     Manual 5-spd  Rear-Wheel Drive

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18
1      Special Purpose Vehicle 2WD   Regular          25.354615        13
2      Special Purpose Vehicle 2WD   Regular          20.600625        16
3      Special Purpose Vehicle 2WD   Regular          25.354615        13
4                     Midsize Cars   Premium          20.600625        14
...                            ...       ...                ...       ...
35947                  Two Seaters   Premium           9.155833        34
35948                  Two Seaters   Premium           9.155833        34
35949                  Two Seaters   Premium           9.155833        34
35950                  Two Seaters   Premium           9.155833        34
35951                  Two Seaters   Premium           9.417429        32

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year
0               17            17               522.764706            1950
1               13            13               683.615385            2550
2               17            16               555.437500            2100
3               13            13               683.615385            2550
4               21            16               555.437500            2550
...            ...           ...                      ...             ...
35947           38            36               244.000000            1100
35948           38            36               243.000000            1100
35949           38            36               244.000000            1100
35950           39            36               246.000000            1100
35951           39            35               255.000000            1150

[35952 rows x 15 columns]>

### Cleaning and wrangling data

- Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use `loc` with boolean indexing.

- Convert CO2 Emissions from Grams/Mile to Grams/Km

- Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use `pandas.Series.str.startswith` and .

- convert MPG columns to km_per_liter

In [336]:
vehicles_df.info() ## interogate the info data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Make                     35952 non-null  object
 1   Model                    35952 non-null  object
 2   Year                     35952 non-null  int64
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  float64
 5   Transmission             35952 non-null  object
 6   Drivetrain               35952 non-null  object
 7   Vehicle Class            35952 non-null  object
 8   Fuel Type                35952 non-null  object
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64
 11  Highway MPG              35952 non-null  int64
 12  Combined MPG             35952 non-null  int64
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year           35952 non-null  int64
dtypes: float64(4), int64(5), object(6)
memory usage: 4.1+ MB

In [337]:
vehicles_Dutton=vehicles_df['Make'] ## Identify Colomn Make
vehicles_Dutton

0              AM General
1              AM General
2              AM General
3              AM General
4        ASC Incorporated
               ...
35947               smart
35948               smart
35949               smart
35950               smart
35951               smart
Name: Make, Length: 35952, dtype: object

In [338]:
vehicles_df["Make"].str.contains("Dutton") ## we see where it is 'Dutton'

0        False
1        False
2        False
3        False
4        False
         ...
35947    False
35948    False
35949    False
35950    False
35951    False
Name: Make, Length: 35952, dtype: bool

In [339]:
vehicles_df["Make"][vehicles_df["Make"].str.contains("Dutton")] = "Dutton" ## we replace whith 'Dutton'

/var/folders/cj/gbt4rs1d4tx3brkqknks4y5r0000gn/T/ipykernel_46534/279847307.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vehicles_df["Make"][vehicles_df["Make"].str.contains("Dutton")] = "Dutton" ## we replace whith 'Dutton'

In [340]:
vehicles_df["Make"][vehicles_df["Make"].str.contains("Dutton")]

11012    Dutton
30164    Dutton
31754    Dutton
Name: Make, dtype: object

In [341]:
vehicles_df.Make.value_counts() ## we identify all vehicle Make

Chevrolet                           3643
Ford                                2946
Dodge                               2360
GMC                                 2347
Toyota                              1836
BMW                                 1677
Mercedes-Benz                       1284
Nissan                              1253
Volkswagen                          1047
Mitsubishi                           950
Mazda                                915
Audi                                 890
Porsche                              862
Honda                                836
Jeep                                 829
Pontiac                              784
Subaru                               781
Volvo                                717
Hyundai                              662
Chrysler                             641
Buick                                537
Mercury                              532
Suzuki                               512
Cadillac                             508
Kia                                  493
Plymouth                             456
Saab                                 410
Isuzu                                409
Lexus                                397
Oldsmobile                           376
Infiniti                             345
Jaguar                               343
MINI                                 320
Acura                                302
Saturn                               278
Lincoln                              273
Ferrari                              208
Rolls-Royce                          160
Eagle                                156
Geo                                  144
Land Rover                           142
Aston Martin                         133
Bentley                              116
Maserati                             111
Lamborghini                          104
Scion                                 83
Peugeot                               74
Daewoo                                67
Ram                                   57
Lotus                                 53
Roush Performance                     53
Fiat                                  43
Alfa Romeo                            41
J.K. Motors                           36
Renault                               33
Wallace Environmental                 32
Maybach                               31
American Motors Corporation           22
smart                                 20
Hummer                                19
Daihatsu                              17
CX Automotive                         16
Merkur                                14
Federal Coach                         14
Import Trade Services                 13
McLaren Automotive                    13
Spyker                                13
Sterling                              12
Bugatti                                8
Yugo                                   8
Genesis                                7
Tecstar, LP                            6
Mcevoy Motors                          6
Bertone                                5
VPG                                    5
Saleen                                 5
Panther Car Company Limited            4
Saleen Performance                     4
AM General                             4
Grumman Olson                          4
Texas Coach Company                    4
Vector                                 4
Autokraft Limited                      4
TVR Engineering Ltd                    4
Bitter Gmbh and Co. Kg                 3
Evans Automobiles                      3
BMW Alpina                             3
Consulier Industries Inc               3
Dabryan Coach Builders Inc             3
Dacia                                  3
Dutton                                 3
Morgan                                 3
Ruf Automobile Gmbh                    2
Bill Dovell Motor Car Company          2
Mobility Ventures LLC                  2
Laforza Automobile Inc                 2
CCC Engineering                        2
PAS Inc - GMC                          2
PAS, Inc                               2
SRT                                    2
Pagani                                 2
Red Shift Ltd.                         2
Pininfarina                            2
Quantum Technologies                   2
Isis Imports Ltd                       1
Mahindra                               1
ASC Incorporated                       1
Aurora Cars Ltd                        1
Volga Associated Automobile            1
Vixen Motor Company                    1
JBA Motorcars, Inc.                    1
London Coach Co Inc                    1
London Taxi                            1
Import Foreign Auto Sales Inc          1
Environmental Rsch and Devp Corp       1
Grumman Allied Industries              1
Goldacre                               1
General Motors                         1
Shelby                                 1
Fisker                                 1
Panos                                  1
Panoz Auto-Development                 1
Excalibur Autos                        1
Qvale                                  1
Lambda Control Systems                 1
Name: Make, dtype: int64

In [342]:
##vehicles_df["Make"][vehicles_df["Make"].str.contains(":")]

Converting Grams/Mile to Grams/Km

1 Mile = 1.60934 Km

Grams/Mile * Mile/Km -> Grams/Mile * 1 Mile/1.60934Km

$$ \frac{Grams}{Mile} * \frac{Mile}{Km} $$

$$ \frac{Grams}{Mile} * \frac{1 Mile}{1.60934Km}  $$

In [343]:
vehicles_df["CO2 Emission Grams/Mile"] = vehicles_df["CO2 Emission Grams/Mile"] / 1.60934
vehicles_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,324.831736,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,345.133719,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,345.133719,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.614948,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,150.993575,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.614948,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,152.857693,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,158.450048,1150

convert MPG columns to km_per_liter

MPG = Miles/Gallon -> Km/Liter

1 Mile = 1.60934 Km

1 Gallon = 3.78541 Liters

$$ \frac{Miles}{Gallon} -> \frac{Miles}{Gallon} * \frac{Km}{Miles} * \frac{Gallon}{Liters}$$

$$ \frac{Miles}{Gallon} -> \frac{Miles}{Gallon} * \frac{1.60934Km}{ 1Miles} * \frac{1 Gallon}{3.78541 Liters}$$

* ( 1.60934 / 3.78541 )

Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use pandas.Series.str.startswith

In [344]:
transmission_df = vehicles_df.Transmission
print (transmission_df)

0        Automatic 3-spd
1        Automatic 3-spd
2        Automatic 3-spd
3        Automatic 3-spd
4        Automatic 4-spd
              ...
35947          Auto(AM5)
35948          Auto(AM5)
35949          Auto(AM5)
35950          Auto(AM6)
35951       Manual 5-spd
Name: Transmission, Length: 35952, dtype: object

In [345]:
transmission_df.str.startswith('Auto')

0         True
1         True
2         True
3         True
4         True
         ...
35947     True
35948     True
35949     True
35950     True
35951    False
Name: Transmission, Length: 35952, dtype: bool

Convert MPG columns to km per liter (City MPG, Highway MPG, Combined MPG)

In [346]:
vehicles_df["City MPG"] = vehicles_df["City MPG"] * 1.60934 /3.78541

vehicles_df["Highway MPG"] = vehicles_df["Highway MPG"] * 1.60934 /3.78541

vehicles_df["Combined MPG"] = vehicles_df["Combined MPG"] * 1.60934 /3.78541

vehicles_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,7.652571,7.227428,7.227428,324.831736,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,5.526857,5.526857,5.526857,424.779962,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,6.802286,7.227428,6.802286,345.133719,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,5.526857,5.526857,5.526857,424.779962,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,5.952000,8.928000,6.802286,345.133719,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14.454857,16.155428,15.305143,151.614948,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14.454857,16.155428,15.305143,150.993575,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14.454857,16.155428,15.305143,151.614948,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14.454857,16.580571,15.305143,152.857693,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,13.604571,16.580571,14.880000,158.450048,1150

In [347]:
vehicles_df = vehicles_df.astype({"City MPG":"int","Highway MPG":"int","Combined MPG":"int" })
print(vehicles_df.dtypes)
vehicles_df

Make                        object
Model                       object
Year                         int64
Engine Displacement        float64
Cylinders                  float64
Transmission                object
Drivetrain                  object
Vehicle Class               object
Fuel Type                   object
Fuel Barrels/Year          float64
City MPG                     int64
Highway MPG                  int64
Combined MPG                 int64
CO2 Emission Grams/Mile    float64
Fuel Cost/Year               int64
dtype: object

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,7,7,7,324.831736,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,5,5,5,424.779962,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,6,7,6,345.133719,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,5,5,5,424.779962,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,5,8,6,345.133719,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14,16,15,151.614948,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14,16,15,150.993575,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14,16,15,151.614948,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14,16,15,152.857693,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,13,16,14,158.450048,1150

### Gathering insights:

- How many car makers are there? How many models? Which car maker has the most cars in the dataset?

- When were these cars made? How big is the engine of these cars?

- What's the frequency of different transmissions, drivetrains and fuel types?

- What's the car that consumes the least/most fuel?

In [348]:
len(vehicles_df.Make.value_counts()) # the number von car makers 'Make'

125

In [349]:
len(vehicles_df.Model.value_counts()) # how many models

3608

In [350]:
vehicles_df.Make.value_counts() # Which car makers has the most cars in the dataset

Chevrolet                           3643
Ford                                2946
Dodge                               2360
GMC                                 2347
Toyota                              1836
BMW                                 1677
Mercedes-Benz                       1284
Nissan                              1253
Volkswagen                          1047
Mitsubishi                           950
Mazda                                915
Audi                                 890
Porsche                              862
Honda                                836
Jeep                                 829
Pontiac                              784
Subaru                               781
Volvo                                717
Hyundai                              662
Chrysler                             641
Buick                                537
Mercury                              532
Suzuki                               512
Cadillac                             508
Kia                                  493
Plymouth                             456
Saab                                 410
Isuzu                                409
Lexus                                397
Oldsmobile                           376
Infiniti                             345
Jaguar                               343
MINI                                 320
Acura                                302
Saturn                               278
Lincoln                              273
Ferrari                              208
Rolls-Royce                          160
Eagle                                156
Geo                                  144
Land Rover                           142
Aston Martin                         133
Bentley                              116
Maserati                             111
Lamborghini                          104
Scion                                 83
Peugeot                               74
Daewoo                                67
Ram                                   57
Lotus                                 53
Roush Performance                     53
Fiat                                  43
Alfa Romeo                            41
J.K. Motors                           36
Renault                               33
Wallace Environmental                 32
Maybach                               31
American Motors Corporation           22
smart                                 20
Hummer                                19
Daihatsu                              17
CX Automotive                         16
Merkur                                14
Federal Coach                         14
Import Trade Services                 13
McLaren Automotive                    13
Spyker                                13
Sterling                              12
Bugatti                                8
Yugo                                   8
Genesis                                7
Tecstar, LP                            6
Mcevoy Motors                          6
Bertone                                5
VPG                                    5
Saleen                                 5
Panther Car Company Limited            4
Saleen Performance                     4
AM General                             4
Grumman Olson                          4
Texas Coach Company                    4
Vector                                 4
Autokraft Limited                      4
TVR Engineering Ltd                    4
Bitter Gmbh and Co. Kg                 3
Evans Automobiles                      3
BMW Alpina                             3
Consulier Industries Inc               3
Dabryan Coach Builders Inc             3
Dacia                                  3
Dutton                                 3
Morgan                                 3
Ruf Automobile Gmbh                    2
Bill Dovell Motor Car Company          2
Mobility Ventures LLC                  2
Laforza Automobile Inc                 2
CCC Engineering                        2
PAS Inc - GMC                          2
PAS, Inc                               2
SRT                                    2
Pagani                                 2
Red Shift Ltd.                         2
Pininfarina                            2
Quantum Technologies                   2
Isis Imports Ltd                       1
Mahindra                               1
ASC Incorporated                       1
Aurora Cars Ltd                        1
Volga Associated Automobile            1
Vixen Motor Company                    1
JBA Motorcars, Inc.                    1
London Coach Co Inc                    1
London Taxi                            1
Import Foreign Auto Sales Inc          1
Environmental Rsch and Devp Corp       1
Grumman Allied Industries              1
Goldacre                               1
General Motors                         1
Shelby                                 1
Fisker                                 1
Panos                                  1
Panoz Auto-Development                 1
Excalibur Autos                        1
Qvale                                  1
Lambda Control Systems                 1
Name: Make, dtype: int64

In [351]:
vehicles_df.Make.value_counts().max() # number max of cars made by makers

3643

In [352]:
print(vehicles_df.Make.value_counts().head(1))

Chevrolet    3643
Name: Make, dtype: int64

In [353]:
from collections import Counter

#def return_counter(data_frame, column_name, limit):
 # print(dict(Counter(data_frame[column_name]
  #.values).most_common(limit)))

def return_counter(vehicles_df, Make, limit):
    print(dict(Counter(vehicles_df[Make].value).most_comon(limit)))

When were these cars made?

In [354]:
list(vehicles_df.Year.value_counts())

[1581,
 1264,
 1228,
 1211,
 1198,
 1188,
 1184,
 1183,
 1168,
 1156,
 1139,
 1127,
 1126,
 1124,
 1122,
 1119,
 1113,
 1108,
 1107,
 1099,
 1077,
 1068,
 1034,
 967,
 961,
 928,
 902,
 857,
 828,
 827,
 791,
 767,
 755,
 645]

How big is the engine of these cars?

In [355]:
vehicles_df.sort_values(by='Engine Displacement', ascending=False)

vehicles_df.sort_values(by='Engine Displacement', ascending=False).head(1)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
10889,Dodge,Viper,2017,8.4,10.0,Manual 6-spd,Rear-Wheel Drive,Two Seaters,Premium,23.543571,5,8,5,387.115215,2900
10909,Dodge,Viper Coupe,2010,8.4,10.0,Manual 6-spd,Rear-Wheel Drive,Two Seaters,Premium,20.600625,5,9,6,345.133719,2550
30166,SRT,Viper,2014,8.4,10.0,Manual 6-spd,Rear-Wheel Drive,Two Seaters,Premium,21.974000,5,8,6,377.173251,2700
10911,Dodge,Viper SRT,2016,8.4,10.0,Manual 6-spd,Rear-Wheel Drive,Two Seaters,Premium,21.974000,5,8,6,359.774815,2700
30165,SRT,Viper,2013,8.4,10.0,Manual 6-spd,Rear-Wheel Drive,Two Seaters,Premium,21.974000,5,8,6,377.173251,2700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35939,smart,fortwo cabriolet,2017,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.694412,13,16,14,160.314166,1200
35938,smart,fortwo cabriolet,2017,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.417429,14,16,14,155.964557,1150
3071,BMW,i3 REX,2016,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,17,15,16,22.990791,1050
3069,BMW,i3 REX,2014,0.6,2.0,Auto(A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,17,15,16,24.854909,1050
3070,BMW,i3 REX,2015,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,17,15,16,24.854909,1050

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
10889,Dodge,Viper,2017,8.4,10.0,Manual 6-spd,Rear-Wheel Drive,Two Seaters,Premium,23.543571,5,8,5,387.115215,2900

What's the frequency of different transmissions, drivetrains and fuel types?

In [356]:
print(vehicles_df.Transmission.value_counts()) #frequency of different transmissions

Automatic 4-spd                     10585
Manual 5-spd                         7787
Automatic (S6)                       2631
Automatic 3-spd                      2597
Manual 6-spd                         2423
Automatic 5-spd                      2171
Automatic 6-spd                      1432
Manual 4-spd                         1306
Automatic (S8)                        960
Automatic (S5)                        822
Automatic (variable gear ratios)      675
Automatic 7-spd                       662
Automatic (S7)                        261
Auto(AM-S7)                           256
Automatic 8-spd                       243
Automatic (S4)                        229
Auto(AM7)                             157
Auto(AV-S6)                           145
Auto(AM6)                             110
Auto(AM-S6)                            92
Automatic 9-spd                        90
Manual 3-spd                           74
Manual 7-spd                           68
Auto(AV-S7)                            63
Auto(AV-S8)                            26
Automatic (S9)                         26
Auto(AM5)                              12
Automatic (AV-S6)                       9
Auto(AM-S8)                             6
Auto(AM8)                               5
Automatic (AV)                          4
Automatic (A6)                          4
Automatic (A1)                          3
Manual(M7)                              3
Auto (AV)                               2
Auto(L4)                                2
Auto(L3)                                2
Automatic (AM5)                         2
Auto(AM-S9)                             1
Automatic 6spd                          1
Auto (AV-S6)                            1
Auto (AV-S8)                            1
Auto(A1)                                1
Automatic (AM6)                         1
Manual 5 spd                            1
Name: Transmission, dtype: int64

In [357]:
print(vehicles_df.Drivetrain.value_counts()) # frequency of drivetrain

Front-Wheel Drive             13044
Rear-Wheel Drive              12726
4-Wheel or All-Wheel Drive     6503
All-Wheel Drive                2039
4-Wheel Drive                  1058
2-Wheel Drive                   423
Part-time 4-Wheel Drive         158
2-Wheel Drive, Front              1
Name: Drivetrain, dtype: int64

In [385]:
print(vehicles_df["Fuel Type"].value_counts()) # frequency of Fuel type

Regular                        23587
Premium                         9921
Gasoline or E85                 1195
Diesel                           911
Premium or E85                   121
Midgrade                          74
CNG                               60
Premium and Electricity           20
Gasoline or natural gas           20
Premium Gas or Electricity        17
Regular Gas and Electricity       16
Gasoline or propane                8
Regular Gas or Electricity         2
Name: Fuel Type, dtype: int64

What's the car that consumes the least/most fuel?

In [362]:
vehicles_df.sort_values(by='Fuel Barrels/Year', ascending=False) # consume moust fuel

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17296,Honda,Civic CNG,2009,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Subcompact Cars,CNG,0.066429,10,15,11,157.329913,1100
17396,Honda,Civic Natural Gas,2013,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,11,16,13,135.459257,1000
17398,Honda,Civic Natural Gas,2015,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,11,16,13,135.459257,1000
17397,Honda,Civic Natural Gas,2014,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,11,16,13,135.459257,1000
17395,Honda,Civic Natural Gas,2012,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,11,16,13,142.104437,1000

In [363]:
vehicles_df.sort_values(by='Fuel Barrels/Year', ascending=False).head(1)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800

In [364]:
vehicles_df.sort_values(by='Fuel Barrels/Year', ascending=True) # consume least fuel

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
17396,Honda,Civic Natural Gas,2013,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,11,16,13,135.459257,1000
17395,Honda,Civic Natural Gas,2012,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,11,16,13,142.104437,1000
17397,Honda,Civic Natural Gas,2014,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,11,16,13,135.459257,1000
17398,Honda,Civic Natural Gas,2015,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,11,16,13,135.459257,1000
17288,Honda,Civic CNG,2001,1.7,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,CNG,0.066429,11,13,11,157.329913,1100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800

In [365]:
vehicles_df.sort_values(by='Fuel Barrels/Year', ascending=True).head(1)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
17396,Honda,Civic Natural Gas,2013,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,11,16,13,135.459257,1000

What brand has the worse CO2 Emissions on average?

Hint: use the function `sort_values()`

In [369]:
vehicles_df.sort_values(by='CO2 Emission Grams/Mile', ascending=False)
#vehicles_df.CO2_Emission.value_counts() ## your Code here

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2,4,2,788.877073,5800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7917,Chevrolet,Volt,2017,1.5,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Regular Gas or Electricity,2.006844,18,17,17,31.690010,800
7916,Chevrolet,Volt,2016,1.5,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Regular Gas or Electricity,2.006844,18,17,17,31.690010,800
3070,BMW,i3 REX,2015,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,17,15,16,24.854909,1050
3069,BMW,i3 REX,2014,0.6,2.0,Auto(A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,17,15,16,24.854909,1050
3071,BMW,i3 REX,2016,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,17,15,16,22.990791,1050

Do cars with automatic transmission consume more fuel than cars with manual transmission on average?

In [411]:

    
transmission_df = print(vehicles_df[('Transmission')])
if 'Transmission'= 'auto' count(transmission_df)
#len(vehicles_df['Transmission':'Auto'])

#fuel_df=print(vehicles_df[('Fuel Type')])

#vehicles_df.count('Transmission'=='Auto')
#def Average(lst):
 #   return sum(lst) / len(lst)
#lst = [15, 9, 55, 41, 35, 20, 62, 49]
#average = Average(lst)
#print("Average of the list =", round(average, 2)
#auto = vehicle_df.[('Transmission', 'auto')] # cars with automatic transmission

#len(vehicles_df.Transmission.value_counts()) ## Your Code is here

SyntaxError: invalid syntax (2452430618.py, line 2)