# Pandas: grouping

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
cars_df = pd.read_csv("data/vehicles.csv")

In [ ]:
cars_df.head()

How many Car models?

In [16]:
cars_df.groupby("Model").count()

,Make,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
Model,,,,,,,,,,,,,,
1-Ton Truck 2WD,16,16,16,16,16,16,16,16,16,16,16,16,16,16
100,12,12,12,12,12,12,12,12,12,12,12,12,12,12
100 Wagon,3,3,3,3,3,3,3,3,3,3,3,3,3,3
100 quattro,9,9,9,9,9,9,9,9,9,9,9,9,9,9
100 quattro Wagon,3,3,3,3,3,3,3,3,3,3,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
iQ,5,5,5,5,5,5,5,5,5,5,5,5,5,5
tC,24,24,24,24,24,24,24,24,24,24,24,24,24,24
xA,6,6,6,6,6,6,6,6,6,6,6,6,6,6
xB,22,22,22,22,22,22,22,22,22,22,22,22,22,22
xD,14,14,14,14,14,14,14,14,14,14,14,14,14,14

In [17]:
cars_model = cars_df["Model"].value_counts()

In [18]:
cars_model

F150 Pickup 2WD      197
F150 Pickup 4WD      179
Truck 2WD            173
Mustang              170
Jetta                169
                    ...
C300 Convertible       1
C300 Coupe             1
C300 FFV               1
C320 4matic Sedan      1
DJ Po Vehicle 2WD      1
Name: Model, Length: 3608, dtype: int64

Group by the data by the Make  using count function

In [19]:
cars_df.groupby("Make").count()

,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
Make,,,,,,,,,,,,,,
AM General,4,4,4,4,4,4,4,4,4,4,4,4,4,4
ASC Incorporated,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Acura,302,302,302,302,302,302,302,302,302,302,302,302,302,302
Alfa Romeo,41,41,41,41,41,41,41,41,41,41,41,41,41,41
American Motors Corporation,22,22,22,22,22,22,22,22,22,22,22,22,22,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Volkswagen,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047
Volvo,717,717,717,717,717,717,717,717,717,717,717,717,717,717
Wallace Environmental,32,32,32,32,32,32,32,32,32,32,32,32,32,32
Yugo,8,8,8,8,8,8,8,8,8,8,8,8,8,8
smart,20,20,20,20,20,20,20,20,20,20,20,20,20,20

What brand has the most cars?

In [20]:
total_brands =cars_df.groupby("Make")['Model'].count().sort_values(ascending=False)
total_brands

Make
Chevrolet                             3643
Ford                                  2946
Dodge                                 2360
GMC                                   2347
Toyota                                1836
                                      ...
Excalibur Autos                          1
S and S Coach Company  E.p. Dutton       1
Environmental Rsch and Devp Corp         1
E. P. Dutton, Inc.                       1
Lambda Control Systems                   1
Name: Model, Length: 127, dtype: int64

In [21]:
total_brands = cars_df.groupby("Make")['Model'].count().reset_index()
total_brands[total_brands['Model']==total_brands['Model'].max()]

         Make  Model
20  Chevrolet   3643

In [22]:
total_brands = cars_df.groupby("Make")['Model'].count().reset_index() # we find wich brand hat total model max
total_brands['Model']==total_brands['Model'].max()

0      False
1      False
2      False
3      False
4      False
       ...
122    False
123    False
124    False
125    False
126    False
Name: Model, Length: 127, dtype: bool

In [23]:
cars_df[cars_df['Cylinders']==6] # we check the 6-cylinder cars

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,345.133719,2550
7,Acura,2.2CL/3.0CL,1997,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,16.480500,18,26,20,276.106976,1650
10,Acura,2.3CL/3.0CL,1998,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,16.480500,17,26,20,276.106976,1650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35900,Wallace Environmental,Wetl 300 GE,1991,2.9,6.0,Automatic 4-spd,4-Wheel or All-Wheel Drive,Special Purpose Vehicles,Premium,27.467500,11,13,12,460.178293,3400
35901,Wallace Environmental,Wetl 300 SL,1991,2.9,6.0,Automatic 4-spd,Rear-Wheel Drive,Minicompact Cars,Premium,21.974000,15,16,15,368.142634,2700
35902,Wallace Environmental,Wetl 300 SL,1992,2.9,6.0,Automatic 4-spd,Rear-Wheel Drive,Minicompact Cars,Premium,21.974000,15,16,15,368.142634,2700
35903,Wallace Environmental,Wetl 300 TE,1991,2.9,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize-Large Station Wagons,Premium,21.974000,15,16,15,368.142634,2700
35904,Wallace Environmental,Wetl 300 TE,1992,2.9,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize-Large Station Wagons,Premium,21.974000,15,16,15,368.142634,2700

In [24]:
cars_df[cars_df['Cylinders']==6].shape   # 12765 cars with 6 cylinders

(12765, 15)

In [66]:
#Converting Grams/Mile to Grams/Km
cars_df["CO2 Emission Grams/Mile"] = cars_df["CO2 Emission Grams/Mile"] / 1.60934
cars_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,125.418858,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,164.009276,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,133.257536,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,164.009276,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,133.257536,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,58.539150,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,58.299235,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,58.539150,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,59.018979,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,61.178210,1150

In [26]:
cars_df.sort_values(by='CO2 Emission Grams/Mile', ascending=False) #

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,490.186706,5800
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,490.186706,5800
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,490.186706,5800
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,490.186706,5800
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,490.186706,5800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7917,Chevrolet,Volt,2017,1.5,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Regular Gas or Electricity,2.006844,43,42,42,19.691308,800
7916,Chevrolet,Volt,2016,1.5,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Regular Gas or Electricity,2.006844,43,42,42,19.691308,800
3070,BMW,i3 REX,2015,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,41,37,39,15.444163,1050
3069,BMW,i3 REX,2014,0.6,2.0,Auto(A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,41,37,39,15.444163,1050
3071,BMW,i3 REX,2016,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,41,37,39,14.285851,1050

In [33]:
cars_df['CO2 Emission Grams/Mile'].value_counts()

190.628163    3114
180.595102    2763
171.565347    2697
163.395569    2662
228.753796    2023
              ...
269.500646       1
280.697665       1
309.269366       1
273.729451       1
94.981603        1
Name: CO2 Emission Grams/Mile, Length: 575, dtype: int64

<b>show the average CO2_Emission_Grams/Km  by Brand

In [34]:
cars_df.groupby('Make').mean()

,Year,Engine Displacement,Cylinders,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
Make,,,,,,,,,
AM General,1984.500000,3.350000,5.000000,22.674670,15.000000,15.000000,14.750000,236.047911,2287.500000
ASC Incorporated,1987.000000,3.800000,6.000000,20.600625,14.000000,21.000000,16.000000,214.456684,2550.000000
Acura,2003.493377,2.834768,5.231788,15.673371,18.890728,25.940397,21.506623,163.161917,1852.483444
Alfa Romeo,1991.878049,2.556098,5.317073,17.208234,17.097561,23.902439,19.512195,179.133804,1962.195122
American Motors Corporation,1984.590909,3.813636,5.545455,18.758092,16.045455,20.181818,17.681818,195.275544,1893.181818
...,...,...,...,...,...,...,...,...,...
Volkswagen,2002.928367,2.236008,4.595033,14.594784,21.226361,28.985673,24.093601,151.639180,1579.417383
Volvo,2002.182706,2.504742,4.945607,16.186996,17.981869,25.064156,20.605300,168.265607,1812.273361
Wallace Environmental,1991.500000,4.315625,7.812500,24.404196,12.437500,16.000000,13.875000,254.052633,2996.875000
Yugo,1988.375000,1.200000,4.000000,13.206218,23.000000,28.250000,25.000000,137.479406,1350.000000
smart,2012.500000,0.980000,3.000000,9.208922,33.300000,39.300000,35.800000,95.379505,1110.000000

In [64]:
cars_emission =cars_df[('CO2 Emission Grams/Mile')/ 1.60934].groupby["Make"].mean().sort_values(ascending=False)
cars_emission

TypeError: unsupported operand type(s) for /: 'str' and 'float'

In [45]:
cars_emission = cars_df.groupby("Make")['CO2 Emission Grams/Mile'].mean().reset_index()
cars_emission[cars_emission['CO2 Emission Grams/Mile']==cars_emission['CO2 Emission Grams/Mile'].max()]

       Make  CO2 Emission Grams/Mile
119  Vector               405.084847

In [46]:
cars_emission['CO2 Emission Grams/Mile']==cars_emission['CO2 Emission Grams/Mile']

0      True
1      True
2      True
3      True
4      True
       ...
122    True
123    True
124    True
125    True
126    True
Name: CO2 Emission Grams/Mile, Length: 127, dtype: bool

In [47]:
cars_df.groupby(['Make','CO2 Emission Grams/Mile']).mean()

                                            Year  Engine Displacement  \
Make             CO2 Emission Grams/Mile
AM General       201.841585               1984.0                  2.5
                 214.456684               1985.0                  2.5
                 263.946688               1984.5                  4.2
ASC Incorporated 214.456684               1987.0                  3.8
Acura            88.031730                2013.5                  1.5
...                                          ...                  ...
smart            94.981603                2016.0                  0.9
                 95.314082                2010.0                  1.0
                 96.912124                2017.0                  0.9
                 98.456540                2016.0                  0.9
                 99.614852                2017.0                  0.9

                                          Cylinders  Fuel Barrels/Year  \
Make             CO2 Emission Grams/Mile
AM General       201.841585                     4.0          19.388824
                 214.456684                     4.0          20.600625
                 263.946688                     6.0          25.354615
ASC Incorporated 214.456684                     6.0          20.600625
Acura            88.031730                      4.0           8.673947
...                                             ...                ...
smart            94.981603                      3.0           9.155833
                 95.314082                      3.0           9.155833
                 96.912124                      3.0           9.417429
                 98.456540                      3.0           9.417429
                 99.614852                      3.0           9.694412

                                          City MPG  Highway MPG  Combined MPG  \
Make             CO2 Emission Grams/Mile
AM General       201.841585                   18.0         17.0          17.0
                 214.456684                   16.0         17.0          16.0
                 263.946688                   13.0         13.0          13.0
ASC Incorporated 214.456684                   14.0         21.0          16.0
Acura            88.031730                    39.0         38.0          38.0
...                                            ...          ...           ...
smart            94.981603                    34.0         39.0          36.0
                 95.314082                    33.2         40.4          36.0
                 96.912124                    33.0         38.0          35.0
                 98.456540                    32.0         39.0          35.0
                 99.614852                    31.0         38.0          34.0

                                          Fuel Cost/Year
Make             CO2 Emission Grams/Mile
AM General       201.841585                       1950.0
                 214.456684                       2100.0
                 263.946688                       2550.0
ASC Incorporated 214.456684                       2550.0
Acura            88.031730                        1050.0
...                                                  ...
smart            94.981603                        1100.0
                 95.314082                        1100.0
                 96.912124                        1150.0
                 98.456540                        1150.0
                 99.614852                        1200.0

[3582 rows x 8 columns]

In [ ]:
### your code us here

<b>show the average CO2_Emission_Grams/Km  by Brand ... sorted

In [ ]:
### your code us here

Use `pd.cut` or `pd.qcut` to create 4 groups (bins) of cars, by Year. We want to explore how cars have evolved decade by decade.

In [49]:
cars_df['Year'].describe()

count    35952.00000
mean      2000.71640
std         10.08529
min       1984.00000
25%       1991.00000
50%       2001.00000
75%       2010.00000
max       2017.00000
Name: Year, dtype: float64

In [62]:
pd.cut(cars_df.Year, bins=4, right=True).head()
 ## your code here

0    (1983.967, 1992.25]
1    (1983.967, 1992.25]
2    (1983.967, 1992.25]
3    (1983.967, 1992.25]
4    (1983.967, 1992.25]
Name: Year, dtype: category
Categories (4, interval[float64, right]): [(1983.967, 1992.25] < (1992.25, 2000.5] < (2000.5, 2008.75] < (2008.75, 2017.0]]

### Did cars consume more gas in the eighties?

show the average City_Km/Liter by year_range

In [61]:
 ### your code is here

Which brands are more environment friendly?

In [70]:
cars_df.groupby(["Make","CO2 Emission Grams/Mile"]).max() ### your code is here
##cars_df["CO2 Emission Grams/Mile"]

                                                        Model  Year  \
Make             CO2 Emission Grams/Mile
AM General       125.418858                 DJ Po Vehicle 2WD  1984
                 133.257536               Post Office DJ5 2WD  1985
                 164.009276               Post Office DJ8 2WD  1985
ASC Incorporated 133.257536                               GNX  1987
Acura            54.700517                         ILX Hybrid  2014
...                                                       ...   ...
smart            59.018979                       fortwo coupe  2016
                 59.225572                       fortwo coupe  2012
                 60.218551                   fortwo cabriolet  2017
                 61.178210                       fortwo coupe  2016
                 61.897953                   fortwo cabriolet  2017

                                          Engine Displacement  Cylinders  \
Make             CO2 Emission Grams/Mile
AM General       125.418858                               2.5        4.0
                 133.257536                               2.5        4.0
                 164.009276                               4.2        6.0
ASC Incorporated 133.257536                               3.8        6.0
Acura            54.700517                                1.5        4.0
...                                                       ...        ...
smart            59.018979                                0.9        3.0
                 59.225572                                1.0        3.0
                 60.218551                                0.9        3.0
                 61.178210                                0.9        3.0
                 61.897953                                0.9        3.0

                                             Transmission         Drivetrain  \
Make             CO2 Emission Grams/Mile
AM General       125.418858               Automatic 3-spd      2-Wheel Drive
                 133.257536               Automatic 3-spd   Rear-Wheel Drive
                 164.009276               Automatic 3-spd   Rear-Wheel Drive
ASC Incorporated 133.257536               Automatic 4-spd   Rear-Wheel Drive
Acura            54.700517                    Auto(AV-S7)  Front-Wheel Drive
...                                                   ...                ...
smart            59.018979                      Auto(AM6)   Rear-Wheel Drive
                 59.225572                 Automatic (S5)   Rear-Wheel Drive
                 60.218551                      Auto(AM6)   Rear-Wheel Drive
                 61.178210                   Manual 5-spd   Rear-Wheel Drive
                 61.897953                   Manual 5-spd   Rear-Wheel Drive

                                                        Vehicle Class  \
Make             CO2 Emission Grams/Mile
AM General       125.418858               Special Purpose Vehicle 2WD
                 133.257536               Special Purpose Vehicle 2WD
                 164.009276               Special Purpose Vehicle 2WD
ASC Incorporated 133.257536                              Midsize Cars
Acura            54.700517                               Compact Cars
...                                                               ...
smart            59.018979                                Two Seaters
                 59.225572                                Two Seaters
                 60.218551                                Two Seaters
                 61.178210                                Two Seaters
                 61.897953                                Two Seaters

                                         Fuel Type  Fuel Barrels/Year  \
Make             CO2 Emission Grams/Mile
AM General       125.418858                Regular          19.388824
                 133.257536                Regular          20.600625
                 164.009276                Regular          25.354615
ASC Incorporated 133.257536                Premium          20.600625
Acura            54.700517                 Premium           8.673947
...                                            ...                ...
smart            59.018979                 Premium           9.155833
                 59.225572                 Premium           9.155833
                 60.218551                 Premium           9.417429
                 61.178210                 Premium           9.417429
                 61.897953                 Premium           9.694412

                                          City MPG  Highway MPG  Combined MPG  \
Make             CO2 Emission Grams/Mile
AM General       125.418858                     18           17            17
                 133.257536                     16           17            16
                 164.009276                     13           13            13
ASC Incorporated 133.257536                     14           21            16
Acura            54.700517                      39           38            38
...                                            ...          ...           ...
smart            59.018979                      34           39            36
                 59.225572                      34           41            36
                 60.218551                      33           38            35
                 61.178210                      32           39            35
                 61.897953                      31           38            34

                                          Fuel Cost/Year
Make             CO2 Emission Grams/Mile
AM General       125.418858                         1950
                 133.257536                         2100
                 164.009276                         2550
ASC Incorporated 133.257536                         2550
Acura            54.700517                          1050
...                                                  ...
smart            59.018979                          1100
                 59.225572                          1100
                 60.218551                          1150
                 61.178210                          1150
                 61.897953                          1200

[3582 rows x 13 columns]

Does the drivetrain affect fuel consumption?

In [71]:
print(cars_df.Transmission.value_counts()) ##frequency of different transmission

Automatic 4-spd                     10585
Manual 5-spd                         7787
Automatic (S6)                       2631
Automatic 3-spd                      2597
Manual 6-spd                         2423
Automatic 5-spd                      2171
Automatic 6-spd                      1432
Manual 4-spd                         1306
Automatic (S8)                        960
Automatic (S5)                        822
Automatic (variable gear ratios)      675
Automatic 7-spd                       662
Automatic (S7)                        261
Auto(AM-S7)                           256
Automatic 8-spd                       243
Automatic (S4)                        229
Auto(AM7)                             157
Auto(AV-S6)                           145
Auto(AM6)                             110
Auto(AM-S6)                            92
Automatic 9-spd                        90
Manual 3-spd                           74
Manual 7-spd                           68
Auto(AV-S7)                            63
Auto(AV-S8)                            26
Automatic (S9)                         26
Auto(AM5)                              12
Automatic (AV-S6)                       9
Auto(AM-S8)                             6
Auto(AM8)                               5
Automatic (AV)                          4
Automatic (A6)                          4
Automatic (A1)                          3
Manual(M7)                              3
Auto (AV)                               2
Auto(L4)                                2
Auto(L3)                                2
Automatic (AM5)                         2
Auto(AM-S9)                             1
Automatic 6spd                          1
Auto (AV-S6)                            1
Auto (AV-S8)                            1
Auto(A1)                                1
Automatic (AM6)                         1
Manual 5 spd                            1
Name: Transmission, dtype: int64

In [72]:
print(cars_df.Drivetrain.value_counts()) # frequency of drivetrain

Front-Wheel Drive             13044
Rear-Wheel Drive              12726
4-Wheel or All-Wheel Drive     6503
All-Wheel Drive                2039
4-Wheel Drive                  1058
2-Wheel Drive                   423
Part-time 4-Wheel Drive         158
2-Wheel Drive, Front              1
Name: Drivetrain, dtype: int64

In [73]:
print(cars_df["Fuel Type"].value_counts()) # frequency of Fuel type

Regular                        23587
Premium                         9921
Gasoline or E85                 1195
Diesel                           911
Premium or E85                   121
Midgrade                          74
CNG                               60
Premium and Electricity           20
Gasoline or natural gas           20
Premium Gas or Electricity        17
Regular Gas and Electricity       16
Gasoline or propane                8
Regular Gas or Electricity         2
Name: Fuel Type, dtype: int64

Do cars with automatic transmission consume more fuel than cars with manual transmission?

In [74]:
cars_df.sort_values(by='Fuel Barrels/Year', ascending=False) # consume moust fuel

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,304.588655,5800
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,304.588655,5800
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,304.588655,5800
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,304.588655,5800
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,6,10,7,304.588655,5800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17296,Honda,Civic CNG,2009,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Subcompact Cars,CNG,0.066429,24,36,28,60.745721,1100
17396,Honda,Civic Natural Gas,2013,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,27,38,31,52.301371,1000
17398,Honda,Civic Natural Gas,2015,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,27,38,31,52.301371,1000
17397,Honda,Civic Natural Gas,2014,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,27,38,31,52.301371,1000
17395,Honda,Civic Natural Gas,2012,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,27,38,31,54.867103,1000

Use `groupby` and `aggregate` with different aggregation measures for different columns:

aggregate with average City_Km/Liter and the count of the Trans

In [ ]:
## your code is here

aggregate with average City_Km/Liter and the minimum of the Trans

In [ ]:
### your code is here